- name: Actualizamos Paquetes
  apt: update_cache=yes upgrade=yes

- name: Instalar Paquetes
  apt:
    name: resolvconf

- name: Copiar clave ssh personal a las maquinas.
  authorized_key:
    user: vagrant
    state: present
    key: "{{ lookup('file', '/home/davidrg/.ssh/id_rsa.pub') }}"
