- name: Activar ip forwarding.
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes


- name: Copiar configuración de red
  ansible.builtin.copy:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'
  notify:
    - Cargar nueva configuracion de red
